dist: trusty
sudo: required
language: node_js
os: linux
node_js:
  node
install:
  - cd application-service
  - npm install
  - npm install -g codecov
script:
  - npm run lint
  - npm test
  - codecov
