version: "2"
services:

  db:
    container_name: db
    restart: always
    build: ./database-service
    ports:
      - "3306:3306"

  app:
    container_name: app
    restart: always
    build: ./application-service
    volumes:
      - ./application-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
